### ISSUE TITLE
static public var dyAlertSettings = DYAlertSettings()

### ISSUE THREAD

**Issue by pfk3** [DominikButz/DYAlertController#2]
First of all, thanks for your great work!

Here is my issue:

I want all of the alerts in my app to share the same DYAlertSettings so they all have the same colors, fonts, etc. but right now DYAlertSettings is internal to your Pod so I need to set fonts, colors, etc. every single time in my code I instantiate an alert.

So what I tried to do is simply try to add a static DYAlertSettings in my AppDelegate:

static public var dyAlertSettings = DYAlertSettings()

And then I could simply say:

alert.settings = AppDelegate. dyAlertSettings

But when I try to add the static DYAlertSettings variable to my AppDelegate, I get an error:

'DYAlertSettings' initializer is inaccessible due to 'internal' protection level

Now I can fix this in my personal branch, but it would mean having to do so each time the Pod changes.

What would be helpful is if you added the static DYAlertSettings variable to the DYAlertController class:

static public var defaults: DYAlertSettings? = nil

Then in the DYAlertController class initializers, if DYAlertController.defaults != nil, you simply apply those defaults to any alert which is instantiated. This allows anyone using your UIAlertController replacement to easily set up common fonts and colors for all of their alerts simply by putting a couple of lines in their code:

DYAlertController.defaults = DYAlertSettings()
/*
.
. Modify any of the defaults to change the fonts, colors, etc. for all instantiations of DYAlertController
.
*/

Now all of my alerts can easily share the same fonts, colors, etc. without me having to put the same code 50 different times in my app to change an alert's fonts, colors, etc. I can still change the fonts, colors, etc. for a specific alert if I want but I don't need to unless I want to deviate from the defaults.

I could do this work and submit it to you if you like, but I don't want to do it if I need to manually keep my changes in sync with your Pod.

Thoughts?

**Comment by DominikButz** [comment]
Hi,
thanks for the question. Actually, DYAlertSettings is a public struct, not an internal one. It might have been internal before but that was probably in a very early version (the latest one is 2.1).

There is a simple solution for your problem: you can create an extension.

Afterwards, in any view controller where you want to create an alert or action sheet, you can do it this way:

```

        let alert = DYAlertController(style: .alert, title: "Export Event", titleIconImage: #imageLiteral(resourceName: "calendarGlyphicon"), message: "Would you like to export this visit as calendar event?", cancelButtonTitle: "No", checkmarks: .none, customFrameWidth: self.view.frame.size.width * 0.75, backgroundEffect: .blur)
        
alert.customSettings()

// add more code, e.g. add an OK action etc.

```


I use DYAlertController myself in an app I'm working on and the colour palette is different from the default, so I also use an extension to adapt it to the app colour scheme. 


Example for an extension (the UIColors don't exist, I have written extensions for those, too):

```
extension DYAlertController {

    func customSettings() {
        
        self.settings.titleTextColor = UIColor.darkIconColor()
        self.settings.titleViewBackgroundColor = UIColor.alertBackground()
        self.settings.messageTextColor = UIColor.darkGray
        self.settings.mainViewBackgroundColor = UIColor.alertBackground()
          self.settings.titleIconTintColor = UIColor.darkIconColor()
        self.settings.cancelButtonTintColorDefault = UIColor.activeElement()
          self.settings.okButtonTintColorDefault = UIColor.activeElement()
        self.settings.okButtonBackgroundColor = UIColor.alertBackground()
        self.settings.cancelButtonBackgroundColor = UIColor.alertBackground()
          self.actionCellSettings.defaultTintColor = UIColor.activeElement()
           self.actionCellSettings.deselectedTintColor = UIColor.lightGray
        self.settings.blurViewStyle = .dark
        self.actionCellSettings.actionCellFont = UIFont.preferredFont(forTextStyle: .body)

       
    }

}
```
Let me know if this solves your problem. 
Kind regards
Dominik

**Comment by pfk3** [comment]
Hah, thanks, I did the same thing in my app except in my extension I called the func "useAppSettings" instead of "customSettings".

**Comment by pfk3** [comment]
And just FYI, I create custom colors in an app by extending UIColor so I can just specify ".myPurple" as the color, just like colors like ".white" and ".red" can be specified in code:

`extension UIColor {
    
    // Create UIColor from an integer (e.g. 0xB142B1)
    convenience init(hex: Int, alpha:CGFloat = 1.0) {
        self.init(
            red:   CGFloat((hex & 0xFF0000) >> 16) / 255.0,
            green: CGFloat((hex & 0x00FF00) >> 8)  / 255.0,
            blue:  CGFloat((hex & 0x0000FF) >> 0)  / 255.0,
            alpha: alpha
        )
    }

    open class var myPurple: UIColor {
        get {
            return UIColor(hex: 0xB142B1)
        }
    }
}
`

**Comment by DominikButz** [comment]
yes, or just create a class func in the UIColor extension. 

```
 class func vcBackground()->UIColor {

      return UIColor(red: 0/255, green: 118/255, blue: 255/255, alpha: 1.0)

 }
```

The better way is probably not using colour names directly but to assign a name that shows it's usage in your app, e.g. "vcBackground".  Then you can change the colour values without having to rename the color. 
Anyway, I'm closing the issue

**Comment by pfk3** [comment]
Hah hah hah, I’m not in the habit of changing my colour names after I create them.
